name: Deploy src folder to GitHub Pages

on:
  push:
    branches:
      - main # 혹은 마스터 브랜치 이름을 입력하세요 (예: master)

# GITHUB_TOKEN의 권한을 GitHub Pages 배포가 가능하도록 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 관리 (이전 배포가 진행 중이면 취소하고 최신 것만 배포)
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 핵심 설정: path에 배포하고자 하는 폴더명(/src)을 지정합니다.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./src"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
